#this is context properties
#Sun Sep 20 23:29:38 CEST 2026
horodatage=
taux_rejet=
version_job=
etape=
nb_lignes_rejetees=
env_nom=local
nom_job=
nb_lignes_inserees=
duree_ms=
index_cible=
donnees_extra={}
message_erreur=
log_repertoire=D\:/Outil_data/projet_data/dwh-melodi/logs
id_execution=
statut=
nb_lignes_lues=
