// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package dwh_melodi.jl_log_execution_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

@SuppressWarnings("unused")

/**
 * Job: jl_log_execution Purpose: <br>
 * Description: <br>
 * 
 * @author user@talend.com
 * @version 7.3.1.20200219_1130
 * @status
 */
public class jl_log_execution implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

			if (horodatage != null) {

				String pattern_horodatage = "yyyy-MM-dd HH:mm:ss";
				String value_horodatage = "";
				String[] parts_horodatage = value_horodatage.split(";");
				if (parts_horodatage.length > 1) {
					pattern_horodatage = parts_horodatage[0];
					this.setProperty("horodatage",
							pattern_horodatage + ";" + FormatterUtils.format_Date(horodatage, pattern_horodatage));
				} else {
					this.setProperty("horodatage", FormatterUtils.format_Date(horodatage, pattern_horodatage));
				}

			}

			if (taux_rejet != null) {

				this.setProperty("taux_rejet", taux_rejet.toString());

			}

			if (version_job != null) {

				this.setProperty("version_job", version_job.toString());

			}

			if (etape != null) {

				this.setProperty("etape", etape.toString());

			}

			if (nb_lignes_rejetees != null) {

				this.setProperty("nb_lignes_rejetees", nb_lignes_rejetees.toString());

			}

			if (env_nom != null) {

				this.setProperty("env_nom", env_nom.toString());

			}

			if (nom_job != null) {

				this.setProperty("nom_job", nom_job.toString());

			}

			if (nb_lignes_inserees != null) {

				this.setProperty("nb_lignes_inserees", nb_lignes_inserees.toString());

			}

			if (duree_ms != null) {

				this.setProperty("duree_ms", duree_ms.toString());

			}

			if (index_cible != null) {

				this.setProperty("index_cible", index_cible.toString());

			}

			if (donnees_extra != null) {

				this.setProperty("donnees_extra", donnees_extra.toString());

			}

			if (message_erreur != null) {

				this.setProperty("message_erreur", message_erreur.toString());

			}

			if (log_repertoire != null) {

				this.setProperty("log_repertoire", log_repertoire.toString());

			}

			if (id_execution != null) {

				this.setProperty("id_execution", id_execution.toString());

			}

			if (statut != null) {

				this.setProperty("statut", statut.toString());

			}

			if (nb_lignes_lues != null) {

				this.setProperty("nb_lignes_lues", nb_lignes_lues.toString());

			}

		}

		public java.util.Date horodatage;

		public java.util.Date getHorodatage() {
			return this.horodatage;
		}

		public String taux_rejet;

		public String getTaux_rejet() {
			return this.taux_rejet;
		}

		public String version_job;

		public String getVersion_job() {
			return this.version_job;
		}

		public String etape;

		public String getEtape() {
			return this.etape;
		}

		public Long nb_lignes_rejetees;

		public Long getNb_lignes_rejetees() {
			return this.nb_lignes_rejetees;
		}

		public String env_nom;

		public String getEnv_nom() {
			return this.env_nom;
		}

		public String nom_job;

		public String getNom_job() {
			return this.nom_job;
		}

		public Long nb_lignes_inserees;

		public Long getNb_lignes_inserees() {
			return this.nb_lignes_inserees;
		}

		public Long duree_ms;

		public Long getDuree_ms() {
			return this.duree_ms;
		}

		public String index_cible;

		public String getIndex_cible() {
			return this.index_cible;
		}

		public String donnees_extra;

		public String getDonnees_extra() {
			return this.donnees_extra;
		}

		public String message_erreur;

		public String getMessage_erreur() {
			return this.message_erreur;
		}

		public String log_repertoire;

		public String getLog_repertoire() {
			return this.log_repertoire;
		}

		public String id_execution;

		public String getId_execution() {
			return this.id_execution;
		}

		public String statut;

		public String getStatut() {
			return this.statut;
		}

		public Long nb_lignes_lues;

		public Long getNb_lignes_lues() {
			return this.nb_lignes_lues;
		}
	}

	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "jl_log_execution";
	private final String projectName = "DWH_MELODI";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();

	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null && currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					jl_log_execution.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(jl_log_execution.this, new Object[] { e, currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void tFixedFlowInput_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFileOutputJSON_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogRow_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFixedFlowInput_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class row2Struct implements routines.system.IPersistableRow<row2Struct> {
		final static byte[] commonByteArrayLock_DWH_MELODI_jl_log_execution = new byte[0];
		static byte[] commonByteArray_DWH_MELODI_jl_log_execution = new byte[0];

		public String id_execution;

		public String getId_execution() {
			return this.id_execution;
		}

		public String nom_job;

		public String getNom_job() {
			return this.nom_job;
		}

		public String version_job;

		public String getVersion_job() {
			return this.version_job;
		}

		public String etape;

		public String getEtape() {
			return this.etape;
		}

		public String statut;

		public String getStatut() {
			return this.statut;
		}

		public java.util.Date horodatage;

		public java.util.Date getHorodatage() {
			return this.horodatage;
		}

		public Long duree_ms;

		public Long getDuree_ms() {
			return this.duree_ms;
		}

		public Long nb_lignes_lues;

		public Long getNb_lignes_lues() {
			return this.nb_lignes_lues;
		}

		public Long nb_lignes_inserees;

		public Long getNb_lignes_inserees() {
			return this.nb_lignes_inserees;
		}

		public Long nb_lignes_rejetees;

		public Long getNb_lignes_rejetees() {
			return this.nb_lignes_rejetees;
		}

		public Float taux_rejet;

		public Float getTaux_rejet() {
			return this.taux_rejet;
		}

		public String message_erreur;

		public String getMessage_erreur() {
			return this.message_erreur;
		}

		public String donnees_extra;

		public String getDonnees_extra() {
			return this.donnees_extra;
		}

		public String environnement;

		public String getEnvironnement() {
			return this.environnement;
		}

		public String index_cible;

		public String getIndex_cible() {
			return this.index_cible;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DWH_MELODI_jl_log_execution.length) {
					if (length < 1024 && commonByteArray_DWH_MELODI_jl_log_execution.length == 0) {
						commonByteArray_DWH_MELODI_jl_log_execution = new byte[1024];
					} else {
						commonByteArray_DWH_MELODI_jl_log_execution = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DWH_MELODI_jl_log_execution, 0, length);
				strReturn = new String(commonByteArray_DWH_MELODI_jl_log_execution, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private java.util.Date readDate(ObjectInputStream dis) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos) throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DWH_MELODI_jl_log_execution) {

				try {

					int length = 0;

					this.id_execution = readString(dis);

					this.nom_job = readString(dis);

					this.version_job = readString(dis);

					this.etape = readString(dis);

					this.statut = readString(dis);

					this.horodatage = readDate(dis);

					length = dis.readByte();
					if (length == -1) {
						this.duree_ms = null;
					} else {
						this.duree_ms = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.nb_lignes_lues = null;
					} else {
						this.nb_lignes_lues = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.nb_lignes_inserees = null;
					} else {
						this.nb_lignes_inserees = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.nb_lignes_rejetees = null;
					} else {
						this.nb_lignes_rejetees = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.taux_rejet = null;
					} else {
						this.taux_rejet = dis.readFloat();
					}

					this.message_erreur = readString(dis);

					this.donnees_extra = readString(dis);

					this.environnement = readString(dis);

					this.index_cible = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.id_execution, dos);

				// String

				writeString(this.nom_job, dos);

				// String

				writeString(this.version_job, dos);

				// String

				writeString(this.etape, dos);

				// String

				writeString(this.statut, dos);

				// java.util.Date

				writeDate(this.horodatage, dos);

				// Long

				if (this.duree_ms == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.duree_ms);
				}

				// Long

				if (this.nb_lignes_lues == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.nb_lignes_lues);
				}

				// Long

				if (this.nb_lignes_inserees == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.nb_lignes_inserees);
				}

				// Long

				if (this.nb_lignes_rejetees == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.nb_lignes_rejetees);
				}

				// Float

				if (this.taux_rejet == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeFloat(this.taux_rejet);
				}

				// String

				writeString(this.message_erreur, dos);

				// String

				writeString(this.donnees_extra, dos);

				// String

				writeString(this.environnement, dos);

				// String

				writeString(this.index_cible, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("id_execution=" + id_execution);
			sb.append(",nom_job=" + nom_job);
			sb.append(",version_job=" + version_job);
			sb.append(",etape=" + etape);
			sb.append(",statut=" + statut);
			sb.append(",horodatage=" + String.valueOf(horodatage));
			sb.append(",duree_ms=" + String.valueOf(duree_ms));
			sb.append(",nb_lignes_lues=" + String.valueOf(nb_lignes_lues));
			sb.append(",nb_lignes_inserees=" + String.valueOf(nb_lignes_inserees));
			sb.append(",nb_lignes_rejetees=" + String.valueOf(nb_lignes_rejetees));
			sb.append(",taux_rejet=" + String.valueOf(taux_rejet));
			sb.append(",message_erreur=" + message_erreur);
			sb.append(",donnees_extra=" + donnees_extra);
			sb.append(",environnement=" + environnement);
			sb.append(",index_cible=" + index_cible);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row2Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row1Struct implements routines.system.IPersistableRow<row1Struct> {
		final static byte[] commonByteArrayLock_DWH_MELODI_jl_log_execution = new byte[0];
		static byte[] commonByteArray_DWH_MELODI_jl_log_execution = new byte[0];

		public String id_execution;

		public String getId_execution() {
			return this.id_execution;
		}

		public String nom_job;

		public String getNom_job() {
			return this.nom_job;
		}

		public String version_job;

		public String getVersion_job() {
			return this.version_job;
		}

		public String etape;

		public String getEtape() {
			return this.etape;
		}

		public String statut;

		public String getStatut() {
			return this.statut;
		}

		public java.util.Date horodatage;

		public java.util.Date getHorodatage() {
			return this.horodatage;
		}

		public Long duree_ms;

		public Long getDuree_ms() {
			return this.duree_ms;
		}

		public Long nb_lignes_lues;

		public Long getNb_lignes_lues() {
			return this.nb_lignes_lues;
		}

		public Long nb_lignes_inserees;

		public Long getNb_lignes_inserees() {
			return this.nb_lignes_inserees;
		}

		public Long nb_lignes_rejetees;

		public Long getNb_lignes_rejetees() {
			return this.nb_lignes_rejetees;
		}

		public Float taux_rejet;

		public Float getTaux_rejet() {
			return this.taux_rejet;
		}

		public String message_erreur;

		public String getMessage_erreur() {
			return this.message_erreur;
		}

		public String donnees_extra;

		public String getDonnees_extra() {
			return this.donnees_extra;
		}

		public String environnement;

		public String getEnvironnement() {
			return this.environnement;
		}

		public String index_cible;

		public String getIndex_cible() {
			return this.index_cible;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DWH_MELODI_jl_log_execution.length) {
					if (length < 1024 && commonByteArray_DWH_MELODI_jl_log_execution.length == 0) {
						commonByteArray_DWH_MELODI_jl_log_execution = new byte[1024];
					} else {
						commonByteArray_DWH_MELODI_jl_log_execution = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DWH_MELODI_jl_log_execution, 0, length);
				strReturn = new String(commonByteArray_DWH_MELODI_jl_log_execution, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private java.util.Date readDate(ObjectInputStream dis) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos) throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DWH_MELODI_jl_log_execution) {

				try {

					int length = 0;

					this.id_execution = readString(dis);

					this.nom_job = readString(dis);

					this.version_job = readString(dis);

					this.etape = readString(dis);

					this.statut = readString(dis);

					this.horodatage = readDate(dis);

					length = dis.readByte();
					if (length == -1) {
						this.duree_ms = null;
					} else {
						this.duree_ms = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.nb_lignes_lues = null;
					} else {
						this.nb_lignes_lues = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.nb_lignes_inserees = null;
					} else {
						this.nb_lignes_inserees = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.nb_lignes_rejetees = null;
					} else {
						this.nb_lignes_rejetees = dis.readLong();
					}

					length = dis.readByte();
					if (length == -1) {
						this.taux_rejet = null;
					} else {
						this.taux_rejet = dis.readFloat();
					}

					this.message_erreur = readString(dis);

					this.donnees_extra = readString(dis);

					this.environnement = readString(dis);

					this.index_cible = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.id_execution, dos);

				// String

				writeString(this.nom_job, dos);

				// String

				writeString(this.version_job, dos);

				// String

				writeString(this.etape, dos);

				// String

				writeString(this.statut, dos);

				// java.util.Date

				writeDate(this.horodatage, dos);

				// Long

				if (this.duree_ms == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.duree_ms);
				}

				// Long

				if (this.nb_lignes_lues == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.nb_lignes_lues);
				}

				// Long

				if (this.nb_lignes_inserees == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.nb_lignes_inserees);
				}

				// Long

				if (this.nb_lignes_rejetees == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeLong(this.nb_lignes_rejetees);
				}

				// Float

				if (this.taux_rejet == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeFloat(this.taux_rejet);
				}

				// String

				writeString(this.message_erreur, dos);

				// String

				writeString(this.donnees_extra, dos);

				// String

				writeString(this.environnement, dos);

				// String

				writeString(this.index_cible, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("id_execution=" + id_execution);
			sb.append(",nom_job=" + nom_job);
			sb.append(",version_job=" + version_job);
			sb.append(",etape=" + etape);
			sb.append(",statut=" + statut);
			sb.append(",horodatage=" + String.valueOf(horodatage));
			sb.append(",duree_ms=" + String.valueOf(duree_ms));
			sb.append(",nb_lignes_lues=" + String.valueOf(nb_lignes_lues));
			sb.append(",nb_lignes_inserees=" + String.valueOf(nb_lignes_inserees));
			sb.append(",nb_lignes_rejetees=" + String.valueOf(nb_lignes_rejetees));
			sb.append(",taux_rejet=" + String.valueOf(taux_rejet));
			sb.append(",message_erreur=" + message_erreur);
			sb.append(",donnees_extra=" + donnees_extra);
			sb.append(",environnement=" + environnement);
			sb.append(",index_cible=" + index_cible);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tFixedFlowInput_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tFixedFlowInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row1Struct row1 = new row1Struct();
				row1Struct row2 = row1;

				/**
				 * [tLogRow_1 begin ] start
				 */

				ok_Hash.put("tLogRow_1", false);
				start_Hash.put("tLogRow_1", System.currentTimeMillis());

				currentComponent = "tLogRow_1";

				if (execStat) {
					runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "row2");
				}

				int tos_count_tLogRow_1 = 0;

				///////////////////////

				final String OUTPUT_FIELD_SEPARATOR_tLogRow_1 = "|";
				java.io.PrintStream consoleOut_tLogRow_1 = null;

				StringBuilder strBuffer_tLogRow_1 = null;
				int nb_line_tLogRow_1 = 0;
///////////////////////    			

				/**
				 * [tLogRow_1 begin ] stop
				 */

				/**
				 * [tFileOutputJSON_1 begin ] start
				 */

				ok_Hash.put("tFileOutputJSON_1", false);
				start_Hash.put("tFileOutputJSON_1", System.currentTimeMillis());

				currentComponent = "tFileOutputJSON_1";

				if (execStat) {
					runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "row1");
				}

				int tos_count_tFileOutputJSON_1 = 0;

				int nb_line_tFileOutputJSON_1 = 0;
				java.io.File file_tFileOutputJSON_1 = new java.io.File(
						context.message_erreur + "/etl-" + TalendDate.getDate("yyyy-MM-dd") + ".ndjson");
				java.io.File dir_tFileOutputJSON_1 = file_tFileOutputJSON_1.getParentFile();
				if (dir_tFileOutputJSON_1 != null && !dir_tFileOutputJSON_1.exists()) {
					dir_tFileOutputJSON_1.mkdirs();
				}
				java.io.PrintWriter outtFileOutputJSON_1 = new java.io.PrintWriter(
						new java.io.BufferedWriter(new java.io.FileWriter(
								context.message_erreur + "/etl-" + TalendDate.getDate("yyyy-MM-dd") + ".ndjson")));
				outtFileOutputJSON_1.append("{\"" + "data" + "\":[");
				boolean isFirst_tFileOutputJSON_1 = true;

				/**
				 * [tFileOutputJSON_1 begin ] stop
				 */

				/**
				 * [tFixedFlowInput_1 begin ] start
				 */

				ok_Hash.put("tFixedFlowInput_1", false);
				start_Hash.put("tFixedFlowInput_1", System.currentTimeMillis());

				currentComponent = "tFixedFlowInput_1";

				int tos_count_tFixedFlowInput_1 = 0;

				for (int i_tFixedFlowInput_1 = 0; i_tFixedFlowInput_1 < 1; i_tFixedFlowInput_1++) {

					row1.id_execution = context.id_execution;

					row1.nom_job = context.nom_job;

					row1.version_job = context.version_job;

					row1.etape = context.etape;

					row1.statut = context.statut;

					row1.horodatage = TalendDate.getCurrentDate();

					row1.duree_ms = context.duree_ms;

					row1.nb_lignes_lues = context.nb_lignes_lues;

					row1.nb_lignes_inserees = context.nb_lignes_inserees;

					row1.nb_lignes_rejetees = context.nb_lignes_rejetees;

					row1.taux_rejet = context.nb_lignes_lues == 0 ? 0f
							: (float) context.nb_lignes_rejetees / context.nb_lignes_lues;

					row1.message_erreur = context.message_erreur;

					row1.donnees_extra = context.donnees_extra;

					row1.environnement = context.index_cible;

					row1.index_cible = context.index_cible;

					/**
					 * [tFixedFlowInput_1 begin ] stop
					 */

					/**
					 * [tFixedFlowInput_1 main ] start
					 */

					currentComponent = "tFixedFlowInput_1";

					tos_count_tFixedFlowInput_1++;

					/**
					 * [tFixedFlowInput_1 main ] stop
					 */

					/**
					 * [tFixedFlowInput_1 process_data_begin ] start
					 */

					currentComponent = "tFixedFlowInput_1";

					/**
					 * [tFixedFlowInput_1 process_data_begin ] stop
					 */

					/**
					 * [tFileOutputJSON_1 main ] start
					 */

					currentComponent = "tFileOutputJSON_1";

					if (execStat) {
						runStat.updateStatOnConnection(iterateId, 1, 1, "row1");
					}

					org.json.simple.JSONObject jsonRowtFileOutputJSON_1 = new org.json.simple.JSONObject();
					if (row1.id_execution != null) {

						jsonRowtFileOutputJSON_1.put("id_execution", row1.id_execution);

					} else {
						jsonRowtFileOutputJSON_1.put("id_execution", null);
					}

					if (row1.nom_job != null) {

						jsonRowtFileOutputJSON_1.put("nom_job", row1.nom_job);

					} else {
						jsonRowtFileOutputJSON_1.put("nom_job", null);
					}

					if (row1.version_job != null) {

						jsonRowtFileOutputJSON_1.put("version_job", row1.version_job);

					} else {
						jsonRowtFileOutputJSON_1.put("version_job", null);
					}

					if (row1.etape != null) {

						jsonRowtFileOutputJSON_1.put("etape", row1.etape);

					} else {
						jsonRowtFileOutputJSON_1.put("etape", null);
					}

					if (row1.statut != null) {

						jsonRowtFileOutputJSON_1.put("statut", row1.statut);

					} else {
						jsonRowtFileOutputJSON_1.put("statut", null);
					}

					if (row1.horodatage != null) {

						jsonRowtFileOutputJSON_1.put("horodatage",
								FormatterUtils.format_Date(row1.horodatage, "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));

					} else {
						jsonRowtFileOutputJSON_1.put("horodatage", null);
					}

					if (row1.duree_ms != null) {

						jsonRowtFileOutputJSON_1.put("duree_ms", row1.duree_ms);

					} else {
						jsonRowtFileOutputJSON_1.put("duree_ms", null);
					}

					if (row1.nb_lignes_lues != null) {

						jsonRowtFileOutputJSON_1.put("nb_lignes_lues", row1.nb_lignes_lues);

					} else {
						jsonRowtFileOutputJSON_1.put("nb_lignes_lues", null);
					}

					if (row1.nb_lignes_inserees != null) {

						jsonRowtFileOutputJSON_1.put("nb_lignes_inserees", row1.nb_lignes_inserees);

					} else {
						jsonRowtFileOutputJSON_1.put("nb_lignes_inserees", null);
					}

					if (row1.nb_lignes_rejetees != null) {

						jsonRowtFileOutputJSON_1.put("nb_lignes_rejetees", row1.nb_lignes_rejetees);

					} else {
						jsonRowtFileOutputJSON_1.put("nb_lignes_rejetees", null);
					}

					if (row1.taux_rejet != null) {

						jsonRowtFileOutputJSON_1.put("taux_rejet", row1.taux_rejet);

					} else {
						jsonRowtFileOutputJSON_1.put("taux_rejet", null);
					}

					if (row1.message_erreur != null) {

						jsonRowtFileOutputJSON_1.put("message_erreur", row1.message_erreur);

					} else {
						jsonRowtFileOutputJSON_1.put("message_erreur", null);
					}

					if (row1.donnees_extra != null) {

						jsonRowtFileOutputJSON_1.put("donnees_extra", row1.donnees_extra);

					} else {
						jsonRowtFileOutputJSON_1.put("donnees_extra", null);
					}

					if (row1.environnement != null) {

						jsonRowtFileOutputJSON_1.put("environnement", row1.environnement);

					} else {
						jsonRowtFileOutputJSON_1.put("environnement", null);
					}

					if (row1.index_cible != null) {

						jsonRowtFileOutputJSON_1.put("index_cible", row1.index_cible);

					} else {
						jsonRowtFileOutputJSON_1.put("index_cible", null);
					}

					if (!isFirst_tFileOutputJSON_1) {
						outtFileOutputJSON_1.append(",");
					}
					isFirst_tFileOutputJSON_1 = false;
					outtFileOutputJSON_1.append(jsonRowtFileOutputJSON_1.toJSONString());
					nb_line_tFileOutputJSON_1++;

					row2 = row1;

					tos_count_tFileOutputJSON_1++;

					/**
					 * [tFileOutputJSON_1 main ] stop
					 */

					/**
					 * [tFileOutputJSON_1 process_data_begin ] start
					 */

					currentComponent = "tFileOutputJSON_1";

					/**
					 * [tFileOutputJSON_1 process_data_begin ] stop
					 */

					/**
					 * [tLogRow_1 main ] start
					 */

					currentComponent = "tLogRow_1";

					if (execStat) {
						runStat.updateStatOnConnection(iterateId, 1, 1, "row2");
					}

///////////////////////		

					strBuffer_tLogRow_1 = new StringBuilder();

					if (row2.id_execution != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.id_execution));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.nom_job != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.nom_job));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.version_job != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.version_job));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.etape != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.etape));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.statut != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.statut));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.horodatage != null) { //

						strBuffer_tLogRow_1
								.append(FormatterUtils.format_Date(row2.horodatage, "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.duree_ms != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.duree_ms));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.nb_lignes_lues != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.nb_lignes_lues));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.nb_lignes_inserees != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.nb_lignes_inserees));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.nb_lignes_rejetees != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.nb_lignes_rejetees));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.taux_rejet != null) { //

						strBuffer_tLogRow_1.append(FormatterUtils.formatUnwithE(row2.taux_rejet));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.message_erreur != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.message_erreur));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.donnees_extra != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.donnees_extra));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.environnement != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.environnement));

					} //

					strBuffer_tLogRow_1.append("|");

					if (row2.index_cible != null) { //

						strBuffer_tLogRow_1.append(String.valueOf(row2.index_cible));

					} //

					if (globalMap.get("tLogRow_CONSOLE") != null) {
						consoleOut_tLogRow_1 = (java.io.PrintStream) globalMap.get("tLogRow_CONSOLE");
					} else {
						consoleOut_tLogRow_1 = new java.io.PrintStream(new java.io.BufferedOutputStream(System.out));
						globalMap.put("tLogRow_CONSOLE", consoleOut_tLogRow_1);
					}
					consoleOut_tLogRow_1.println(strBuffer_tLogRow_1.toString());
					consoleOut_tLogRow_1.flush();
					nb_line_tLogRow_1++;
//////

//////                    

///////////////////////    			

					tos_count_tLogRow_1++;

					/**
					 * [tLogRow_1 main ] stop
					 */

					/**
					 * [tLogRow_1 process_data_begin ] start
					 */

					currentComponent = "tLogRow_1";

					/**
					 * [tLogRow_1 process_data_begin ] stop
					 */

					/**
					 * [tLogRow_1 process_data_end ] start
					 */

					currentComponent = "tLogRow_1";

					/**
					 * [tLogRow_1 process_data_end ] stop
					 */

					/**
					 * [tFileOutputJSON_1 process_data_end ] start
					 */

					currentComponent = "tFileOutputJSON_1";

					/**
					 * [tFileOutputJSON_1 process_data_end ] stop
					 */

					/**
					 * [tFixedFlowInput_1 process_data_end ] start
					 */

					currentComponent = "tFixedFlowInput_1";

					/**
					 * [tFixedFlowInput_1 process_data_end ] stop
					 */

					/**
					 * [tFixedFlowInput_1 end ] start
					 */

					currentComponent = "tFixedFlowInput_1";

				}
				globalMap.put("tFixedFlowInput_1_NB_LINE", 1);

				ok_Hash.put("tFixedFlowInput_1", true);
				end_Hash.put("tFixedFlowInput_1", System.currentTimeMillis());

				/**
				 * [tFixedFlowInput_1 end ] stop
				 */

				/**
				 * [tFileOutputJSON_1 end ] start
				 */

				currentComponent = "tFileOutputJSON_1";

				outtFileOutputJSON_1.print("]}");
				outtFileOutputJSON_1.close();
				globalMap.put("tFileOutputJSON_1_NB_LINE", nb_line_tFileOutputJSON_1);

				if (execStat) {
					runStat.updateStat(resourceMap, iterateId, 2, 0, "row1");
				}

				ok_Hash.put("tFileOutputJSON_1", true);
				end_Hash.put("tFileOutputJSON_1", System.currentTimeMillis());

				/**
				 * [tFileOutputJSON_1 end ] stop
				 */

				/**
				 * [tLogRow_1 end ] start
				 */

				currentComponent = "tLogRow_1";

//////
//////
				globalMap.put("tLogRow_1_NB_LINE", nb_line_tLogRow_1);

///////////////////////    			

				if (execStat) {
					runStat.updateStat(resourceMap, iterateId, 2, 0, "row2");
				}

				ok_Hash.put("tLogRow_1", true);
				end_Hash.put("tLogRow_1", System.currentTimeMillis());

				/**
				 * [tLogRow_1 end ] stop
				 */

			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tFixedFlowInput_1 finally ] start
				 */

				currentComponent = "tFixedFlowInput_1";

				/**
				 * [tFixedFlowInput_1 finally ] stop
				 */

				/**
				 * [tFileOutputJSON_1 finally ] start
				 */

				currentComponent = "tFileOutputJSON_1";

				/**
				 * [tFileOutputJSON_1 finally ] stop
				 */

				/**
				 * [tLogRow_1 finally ] start
				 */

				currentComponent = "tLogRow_1";

				/**
				 * [tLogRow_1 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tFixedFlowInput_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean enableLogStash;

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	private PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final jl_log_execution jl_log_executionClass = new jl_log_execution();

		int exitCode = jl_log_executionClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}
		enableLogStash = "true".equalsIgnoreCase(System.getProperty("monitoring"));

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket can't open
				System.err.println("The statistics socket port " + portStats + " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}

		try {
			// call job/subjob with an existing context, like: --context=production. if
			// without this parameter, there will use the default context instead.
			java.io.InputStream inContext = jl_log_execution.class.getClassLoader()
					.getResourceAsStream("dwh_melodi/jl_log_execution_0_1/contexts/" + contextStr + ".properties");
			if (inContext == null) {
				inContext = jl_log_execution.class.getClassLoader()
						.getResourceAsStream("config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				// defaultProps is in order to keep the original context value
				if (context != null && context.isEmpty()) {
					defaultProps.load(inContext);
					context = new ContextProperties(defaultProps);
				}

				inContext.close();
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
			class ContextProcessing {
				private void processContext_0() {
					context.setContextType("horodatage", "id_Date");
					try {
						String context_horodatage_value = context.getProperty("horodatage");
						if (context_horodatage_value == null) {
							context_horodatage_value = "";
						}
						int context_horodatage_pos = context_horodatage_value.indexOf(";");
						String context_horodatage_pattern = "yyyy-MM-dd HH:mm:ss";
						if (context_horodatage_pos > -1) {
							context_horodatage_pattern = context_horodatage_value.substring(0, context_horodatage_pos);
							context_horodatage_value = context_horodatage_value.substring(context_horodatage_pos + 1);
						}

						context.horodatage = (java.util.Date) (new java.text.SimpleDateFormat(
								context_horodatage_pattern).parse(context_horodatage_value));

					} catch (ParseException e) {
						System.err.println(String.format("Null value will be used for context parameter %s: %s",
								"horodatage", e.getMessage()));
						context.horodatage = null;
					}
					context.setContextType("taux_rejet", "id_String");
					context.taux_rejet = (String) context.getProperty("taux_rejet");
					context.setContextType("version_job", "id_String");
					context.version_job = (String) context.getProperty("version_job");
					context.setContextType("etape", "id_String");
					context.etape = (String) context.getProperty("etape");
					context.setContextType("nb_lignes_rejetees", "id_Long");
					try {
						context.nb_lignes_rejetees = routines.system.ParserUtils
								.parseTo_Long(context.getProperty("nb_lignes_rejetees"));
					} catch (NumberFormatException e) {
						System.err.println(String.format("Null value will be used for context parameter %s: %s",
								"nb_lignes_rejetees", e.getMessage()));
						context.nb_lignes_rejetees = null;
					}
					context.setContextType("env_nom", "id_String");
					context.env_nom = (String) context.getProperty("env_nom");
					context.setContextType("nom_job", "id_String");
					context.nom_job = (String) context.getProperty("nom_job");
					context.setContextType("nb_lignes_inserees", "id_Long");
					try {
						context.nb_lignes_inserees = routines.system.ParserUtils
								.parseTo_Long(context.getProperty("nb_lignes_inserees"));
					} catch (NumberFormatException e) {
						System.err.println(String.format("Null value will be used for context parameter %s: %s",
								"nb_lignes_inserees", e.getMessage()));
						context.nb_lignes_inserees = null;
					}
					context.setContextType("duree_ms", "id_Long");
					try {
						context.duree_ms = routines.system.ParserUtils.parseTo_Long(context.getProperty("duree_ms"));
					} catch (NumberFormatException e) {
						System.err.println(String.format("Null value will be used for context parameter %s: %s",
								"duree_ms", e.getMessage()));
						context.duree_ms = null;
					}
					context.setContextType("index_cible", "id_String");
					context.index_cible = (String) context.getProperty("index_cible");
					context.setContextType("donnees_extra", "id_String");
					context.donnees_extra = (String) context.getProperty("donnees_extra");
					context.setContextType("message_erreur", "id_String");
					context.message_erreur = (String) context.getProperty("message_erreur");
					context.setContextType("log_repertoire", "id_String");
					context.log_repertoire = (String) context.getProperty("log_repertoire");
					context.setContextType("id_execution", "id_String");
					context.id_execution = (String) context.getProperty("id_execution");
					context.setContextType("statut", "id_String");
					context.statut = (String) context.getProperty("statut");
					context.setContextType("nb_lignes_lues", "id_Long");
					try {
						context.nb_lignes_lues = routines.system.ParserUtils
								.parseTo_Long(context.getProperty("nb_lignes_lues"));
					} catch (NumberFormatException e) {
						System.err.println(String.format("Null value will be used for context parameter %s: %s",
								"nb_lignes_lues", e.getMessage()));
						context.nb_lignes_lues = null;
					}
				}

				public void processAllContext() {
					processContext_0();
				}
			}

			new ContextProcessing().processAllContext();
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
			if (parentContextMap.containsKey("horodatage")) {
				context.horodatage = (java.util.Date) parentContextMap.get("horodatage");
			}
			if (parentContextMap.containsKey("taux_rejet")) {
				context.taux_rejet = (String) parentContextMap.get("taux_rejet");
			}
			if (parentContextMap.containsKey("version_job")) {
				context.version_job = (String) parentContextMap.get("version_job");
			}
			if (parentContextMap.containsKey("etape")) {
				context.etape = (String) parentContextMap.get("etape");
			}
			if (parentContextMap.containsKey("nb_lignes_rejetees")) {
				context.nb_lignes_rejetees = (Long) parentContextMap.get("nb_lignes_rejetees");
			}
			if (parentContextMap.containsKey("env_nom")) {
				context.env_nom = (String) parentContextMap.get("env_nom");
			}
			if (parentContextMap.containsKey("nom_job")) {
				context.nom_job = (String) parentContextMap.get("nom_job");
			}
			if (parentContextMap.containsKey("nb_lignes_inserees")) {
				context.nb_lignes_inserees = (Long) parentContextMap.get("nb_lignes_inserees");
			}
			if (parentContextMap.containsKey("duree_ms")) {
				context.duree_ms = (Long) parentContextMap.get("duree_ms");
			}
			if (parentContextMap.containsKey("index_cible")) {
				context.index_cible = (String) parentContextMap.get("index_cible");
			}
			if (parentContextMap.containsKey("donnees_extra")) {
				context.donnees_extra = (String) parentContextMap.get("donnees_extra");
			}
			if (parentContextMap.containsKey("message_erreur")) {
				context.message_erreur = (String) parentContextMap.get("message_erreur");
			}
			if (parentContextMap.containsKey("log_repertoire")) {
				context.log_repertoire = (String) parentContextMap.get("log_repertoire");
			}
			if (parentContextMap.containsKey("id_execution")) {
				context.id_execution = (String) parentContextMap.get("id_execution");
			}
			if (parentContextMap.containsKey("statut")) {
				context.statut = (String) parentContextMap.get("statut");
			}
			if (parentContextMap.containsKey("nb_lignes_lues")) {
				context.nb_lignes_lues = (Long) parentContextMap.get("nb_lignes_lues");
			}
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "",
				"", "", "", "", resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tFixedFlowInput_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tFixedFlowInput_1) {
			globalMap.put("tFixedFlowInput_1_SUBPROCESS_STATE", -1);

			e_tFixedFlowInput_1.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		if (false) {
			System.out.println(
					(endUsedMemory - startUsedMemory) + " bytes memory increase when running : jl_log_execution");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;
		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "",
				"" + returnCode, "", "", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		} else if (arg.startsWith("--monitoring") && arg.contains("=")) {// for trunjob call
			final int equal = arg.indexOf('=');
			final String key = arg.substring("--".length(), equal);
			System.setProperty(key, arg.substring(equal + 1));
		}
	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" }, { "\\'", "\'" }, { "\\r", "\r" },
			{ "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the
			// result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 71248 characters generated by Talend Open Studio for Data Integration on the
 * 20 septembre 2026 23:29:38 CEST
 ************************************************************************************************/